# tests/unit/test_gen_docs.py
from pathlib import Path
import tools.gen_docs as gd


def _make_tree(tmp_path: Path) -> Path:
    pkg = tmp_path / "pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text('"""Pkg root."""\n')
    (pkg / "alpha.py").write_text('"""Computes alpha."""\nX = 1\n')
    (pkg / "beta.py").write_text("X = 2\n")  # no docstring
    return tmp_path


def test_inventory_reads_roles(tmp_path):
    root = _make_tree(tmp_path)
    mods = gd.collect_modules(root, source_roots=["pkg"], toplevel=[])
    by_path = {m.path: m for m in mods}
    assert by_path["pkg/alpha.py"].role == "Computes alpha."
    assert by_path["pkg/beta.py"].role == gd.NO_DOCSTRING
    assert by_path["pkg/__init__.py"].role == "Pkg root."


def test_import_graph_flags_dead(tmp_path):
    root = tmp_path
    pkg = root / "pkg"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "alpha.py").write_text('"""A."""\nX = 1\n')
    (pkg / "beta.py").write_text('"""B."""\nfrom pkg.alpha import X\n')  # imports alpha
    tests = root / "tests"
    tests.mkdir()
    (tests / "test_x.py").write_text("from pkg.beta import X\n")  # test-only importer

    mods = gd.collect_modules(root, source_roots=["pkg"], toplevel=[])
    gd.annotate_importers(root, mods, test_dirs=["tests"])
    by = {m.path: m for m in mods}
    assert by["pkg/alpha.py"].status == "WIRED"   # imported by beta (non-test)
    assert by["pkg/beta.py"].status == "DEAD?"     # only a test imports it


def test_real_tree_wiring_truth():
    """The load-bearing facts the docs must never get wrong."""
    mods = gd.collect_modules(gd.REPO)
    gd.annotate_importers(gd.REPO, mods)
    by = {m.path: m for m in mods}
    # The live loop and its signal math are WIRED.
    assert by["btc_bot/paper.py"].status == "WIRED"
    assert by["btc_bot/strategy.py"].status == "WIRED"
    # The live risk gate + executor are WIRED.
    assert by["btc_5m_fv/execution/gate.py"].status == "WIRED"
    assert by["btc_5m_fv/execution/live.py"].status == "WIRED"
    # Known dead-in-active-tree module is flagged.
    assert by["btc_5m_fv/ops/controller.py"].status == "DEAD?"


def test_test_count_is_positive_int():
    n = gd.count_tests(gd.REPO)
    assert isinstance(n, int) and n > 300  # currently ~488


def test_entrypoint_importable():
    assert gd.entrypoint_ok(gd.REPO) is True  # btc_5m_fv.ops.dashboard.app imports


def test_replace_block_is_idempotent():
    doc = "intro\n<!-- BEGIN GENERATED:x -->\nOLD\n<!-- END GENERATED:x -->\nrest\n"
    once = gd.replace_block(doc, "x", "NEW")
    twice = gd.replace_block(once, "x", "NEW")
    assert "NEW" in once and "OLD" not in once
    assert once == twice  # deterministic / idempotent


def test_render_file_map_deterministic():
    a = gd.render_file_map(gd.REPO)
    b = gd.render_file_map(gd.REPO)
    assert a == b and a.startswith("<!-- GENERATED by tools/gen_docs.py")
